small fixes

diff --git a/src/alvin/Makefile b/src/alvin/Makefile
--- a/src/alvin/Makefile
+++ b/src/alvin/Makefile
@@ -26,7 +26,7 @@ AI_NAME = alvin
 ES_INCS = ${ES_INCLUDE_PATH}
 ES_SRC = $(AI_NAME).es
 ES_TARGET = $(AI_NAME).eso
-ES_TEST = $(AI_NAME).test
+TESTS = $(AI_NAME).test intro_video.test select_image.test
 
 INC = \
 animal.es \
@@ -45,13 +45,22 @@ $(ES_TARGET):	$(ES_SRC) $(INC)
 	$(ESC) -I . -I $(ES_INCS) $< -o $@
 
 test:   $(ES_TARGET)
-	@echo "RUNNING TEST SCRIPT " $(ES_TEST); \
-	$(ESTEST) -r -3 -b $(ES_TEST) $(ES_TARGET); \
-	if [ $$? -eq "0" ]; then \
-		echo "TESTING $(ES_TEST) OK"; \
+	@export TESTS_OK="1"; \
+	for TEST in $(TESTS); do \
+		echo "RUNNING TEST SCRIPT " $${TEST}; \
+		$(ESTEST) -r -3 -b -s $${TEST} $(ES_TARGET); \
+		if [ $$? -eq "0" ]; then \
+			echo "TESTING $${TEST} OK"; \
+		else \
+			echo "TESTING $${TEST} FAIL"; \
+			export TESTS_OK="0"; \
+		fi; \
+	done; \
+	if [ "$${TESTS_OK}" -eq "1" ]; then \
+		echo "TESTS OK"; \
 	else \
-		echo "TESTING $(ES_TEST) FAIL"; \
-	fi
+		echo "TESTS FAILED"; \
+	fi;
 
 clean:
 	rm -f $(ES_TARGET)
